version: "3.7"

########################### NETWORKS
networks:
  default:
    driver: bridge

########################### SERVICES
services:


# Portainer - WebUI for Containers
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    command: -H unix:///var/run/docker.sock
    security_opt:
      - no-new-privileges:true
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ~/.docker/portainer/data:/data 
    environment:
      - TZ="America/Chicago"

#####################################habitica test########################################################
  client:
    build: ~/.docker/habitica
    networks:
      t2_proxy:
    command: ["npm", "run", "client:dev"]
    container_name: hab-client
    depends_on:
      - server
    environment:
      - BASE_URL=http://server:3000 #DON'T CHANGE
    ports:
      - "8085:8080" 
    volumes:
    volumes:
      - ~/.docker/habitica:/usr/src/habitica
      #- /usr/src/habitica/node_modules
      #- /usr/src/habitica/website/client/node_modules

  server:
    build: ~/.docker/habitica
    command: ["npm", "start"]
    container_name: hab-server
    depends_on:
      - mongo
    environment:
      - NODE_DB_URI=mongodb://mongo/habitrpg
    ports:
      - "3005:3000" 
    volumes:
      - ~/.docker/habitica:/usr/src/habitica
      #- /usr/src/habitica/node_modules

  mongo:
    image: mongo:4.2.8
    container_name: mongo
    ports:
      - "27017:27017"
    command: --replSet rs
    volumes:
      - ~/.docker/habitica/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
